id: IAA2EDD54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:42:55+00:00'
last_modified: '2022-06-08T12:12:51.066860+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30102
  title: གསུང་འབུམ། ངག་དབང་བསྟན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D5EE:
      image_group_id: I1KG15025
      title: ''
      total_pages: 592
      order: 1
      base_file: D5EE.txt
    06C3:
      image_group_id: I1KG15026
      title: ''
      total_pages: 594
      order: 2
      base_file: 06C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
